runtime: python311

entrypoint: gunicorn -b :$PORT main:app

env_variables:
  FLASK_APP: main.py
  FLASK_ENV: production

handlers:
- url: /static
  static_dir: static

instance_class: F2

automatic_scaling:
  min_instances: 1
  max_instances: 5
  max_concurrent_requests: 50